/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadorrequisitos;

import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;
import gerenciadorrequisitos.classes.Pessoa;
import gerenciadorrequisitos.painels.AlertLogin;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author allan
 */
public class FormLogin extends javax.swing.JFrame {
    public static Pessoa usuario;
    
    public FormLogin() {
        initComponents();
        
        usuario = new Pessoa();
        
        Font font = lblCadastro.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        lblCadastro.setFont(font.deriveFont(attributes));
        
        txtUsuario.setBorder(BorderFactory.createCompoundBorder(txtUsuario.getBorder(),BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        txtSenha.setBorder(BorderFactory.createCompoundBorder(txtSenha.getBorder(),BorderFactory.createEmptyBorder(0, 5, 0, 0)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        pLogin = new javax.swing.JPanel();
        pDesc = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        pClose = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblSemCadastro = new javax.swing.JLabel();
        pEntrar = new javax.swing.JPanel();
        lblEntrar = new javax.swing.JLabel();
        lblCadastro = new javax.swing.JLabel();
        pSenha = new javax.swing.JPanel();
        txtSenha = new javax.swing.JPasswordField();
        lblMostrarSenha = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();

        lblUsuario.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario.setText("Login");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign up");
        setUndecorated(true);
        setResizable(false);

        pLogin.setBackground(new java.awt.Color(255, 255, 255));
        pLogin.setLayout(null);

        pDesc.setBackground(new java.awt.Color(0, 0, 47));

        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/login.png"))); // NOI18N

        lblDesc.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(255, 255, 255));
        lblDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesc.setText("Bem-vindo(a). Faça login!");

        javax.swing.GroupLayout pDescLayout = new javax.swing.GroupLayout(pDesc);
        pDesc.setLayout(pDescLayout);
        pDescLayout.setHorizontalGroup(
            pDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDescLayout.createSequentialGroup()
                .addGroup(pDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDescLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDescLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        pDescLayout.setVerticalGroup(
            pDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDescLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDesc)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pLogin.add(pDesc);
        pDesc.setBounds(0, 0, 300, 400);

        pClose.setBackground(new java.awt.Color(0, 0, 47));
        pClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pCloseMouseExited(evt);
            }
        });

        lblClose.setBackground(new java.awt.Color(255, 255, 255));
        lblClose.setFont(new java.awt.Font("Verdana", 0, 28)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/delete_32px.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pCloseLayout = new javax.swing.GroupLayout(pClose);
        pClose.setLayout(pCloseLayout);
        pCloseLayout.setHorizontalGroup(
            pCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pCloseLayout.setVerticalGroup(
            pCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCloseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pLogin.add(pClose);
        pClose.setBounds(560, 0, 40, 40);

        lblTitulo.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Login");
        pLogin.add(lblTitulo);
        lblTitulo.setBounds(410, 60, 90, 28);

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuario.setText("Nome de usuário");
        txtUsuario.setToolTipText("");
        txtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        pLogin.add(txtUsuario);
        txtUsuario.setBounds(330, 140, 240, 40);

        lblSenha.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(51, 51, 51));
        lblSenha.setText("Senha");
        pLogin.add(lblSenha);
        lblSenha.setBounds(330, 220, 120, 14);

        lblSemCadastro.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        lblSemCadastro.setForeground(new java.awt.Color(51, 51, 51));
        lblSemCadastro.setText("Não contém um cadastro ainda?");
        pLogin.add(lblSemCadastro);
        lblSemCadastro.setBounds(330, 360, 170, 14);

        pEntrar.setBackground(new java.awt.Color(0, 0, 47));

        lblEntrar.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        lblEntrar.setForeground(new java.awt.Color(255, 255, 255));
        lblEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntrar.setText("Entrar");
        lblEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEntrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pEntrarLayout = new javax.swing.GroupLayout(pEntrar);
        pEntrar.setLayout(pEntrarLayout);
        pEntrarLayout.setHorizontalGroup(
            pEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        pEntrarLayout.setVerticalGroup(
            pEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pLogin.add(pEntrar);
        pEntrar.setBounds(330, 310, 90, 30);

        lblCadastro.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        lblCadastro.setForeground(new java.awt.Color(51, 51, 51));
        lblCadastro.setText("Clique aqui!");
        lblCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadastroMouseExited(evt);
            }
        });
        pLogin.add(lblCadastro);
        lblCadastro.setBounds(500, 360, 60, 15);

        pSenha.setBackground(new java.awt.Color(255, 255, 255));
        pSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pSenha.setMinimumSize(new java.awt.Dimension(136, 23));
        pSenha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSenha.setBackground(new java.awt.Color(255, 255, 255));
        txtSenha.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(204, 204, 204));
        txtSenha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSenha.setText("Senha");
        txtSenha.setToolTipText("");
        txtSenha.setBorder(null);
        txtSenha.setEchoChar('\u0000');
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });
        pSenha.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 190, 38));

        lblMostrarSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMostrarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/eye.png"))); // NOI18N
        lblMostrarSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMostrarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMostrarSenhaMouseClicked(evt);
            }
        });
        pSenha.add(lblMostrarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 50, 38));

        pLogin.add(pSenha);
        pSenha.setBounds(330, 240, 240, 40);

        lblUsuario1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario1.setText("Login");
        pLogin.add(lblUsuario1);
        lblUsuario1.setBounds(330, 120, 120, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(600, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroMouseEntered
        // TODO add your handling code here:
        lblCadastro.setForeground(Color.decode("#000fea"));
    }//GEN-LAST:event_lblCadastroMouseEntered

    private void lblCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroMouseExited
        // TODO add your handling code here:
        lblCadastro.setForeground(Color.decode("#333333"));
    }//GEN-LAST:event_lblCadastroMouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        // TODO add your handling code here:
        if(txtUsuario.getText().equals("Nome de usuário")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        // TODO add your handling code here:
        if(txtUsuario.getText().equals("")) {
            txtUsuario.setText("Nome de usuário");
            txtUsuario.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        // TODO add your handling code here:
        String senha = String.valueOf(txtSenha.getPassword());
        if(senha.equals("Senha") && txtSenha.getForeground().equals(new Color(204,204,204))) {
            txtSenha.setText("");
            txtSenha.setForeground(new Color(51,51,51));
            txtSenha.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
        // TODO add your handling code here:
        String senha = String.valueOf(txtSenha.getPassword());
        if(senha.equals("")) {
            txtSenha.setText("Senha");
            txtSenha.setForeground(new Color(204,204,204));
            txtSenha.setEchoChar('\u0000');
            lblMostrarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/eye.png")));
        }
    }//GEN-LAST:event_txtSenhaFocusLost

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseEntered

    private void pCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCloseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pCloseMouseEntered

    private void pCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCloseMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pCloseMouseExited

    private void lblEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarMouseClicked
        // TODO add your handling code here:
        String user = txtUsuario.getText();        
        String pass = String.valueOf(txtSenha.getPassword());
 
        boolean autenticado = usuario.autenticarUsuario(user, pass);
        
        if (autenticado) JOptionPane.showMessageDialog(null, "Sucesso!");
        if (!autenticado) {
            FormLogin login = new FormLogin();
            AlertLogin alerta = new AlertLogin(login, true);
            alerta.setVisible(true);
        }
    }//GEN-LAST:event_lblEntrarMouseClicked

    private void lblMostrarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMostrarSenhaMouseClicked
        // TODO add your handling code here:
        String senha = String.valueOf(txtSenha.getPassword());

        char echoChar = '\u2022';
        char echoCharUsado = txtSenha.getEchoChar();

        if (senha.equals("Senha") && txtSenha.getForeground().equals(new Color(204,204,204))) {
            txtSenha.setText("");
            txtSenha.grabFocus();
            txtSenha.setForeground(new Color(51,51,51));
        }
        if(echoCharUsado == echoChar) {
            txtSenha.setEchoChar('\u0000');
            lblMostrarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/eyeEsconde.png")));
        }
        if (echoCharUsado != echoChar) {
            txtSenha.setEchoChar('\u2022');
            lblMostrarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/eye.png")));
        }
    }//GEN-LAST:event_lblMostrarSenhaMouseClicked

    private void lblCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroMouseClicked
        // TODO add your handling code here:
        FormCadastroPessoa cadastroPessoa = new FormCadastroPessoa();
        cadastroPessoa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblCadastroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblEntrar;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMostrarSenha;
    private javax.swing.JLabel lblSemCadastro;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JPanel pClose;
    private javax.swing.JPanel pDesc;
    private javax.swing.JPanel pEntrar;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPanel pSenha;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
