/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadorrequisitos;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author allan
 */
public class FormCadastroPessoa extends javax.swing.JFrame {

    /**
     * Creates new form FormCadastroPessoa
     */
    public FormCadastroPessoa() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        txtNomeCompleto.setBorder(BorderFactory.createCompoundBorder(txtNomeCompleto.getBorder(),BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        txtUsuario.setBorder(BorderFactory.createCompoundBorder(txtUsuario.getBorder(),BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        txtTelefone.setBorder(BorderFactory.createCompoundBorder(txtTelefone.getBorder(),BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        txtSenha.setBorder(BorderFactory.createCompoundBorder(txtSenha.getBorder(),BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        txtEmail.setBorder(BorderFactory.createCompoundBorder(txtEmail.getBorder(),BorderFactory.createEmptyBorder(0, 5, 0, 0)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLayout = new javax.swing.JPanel();
        lblImagemCadastro = new javax.swing.JLabel();
        lblCadastrese = new javax.swing.JLabel();
        pDados = new javax.swing.JPanel();
        lblDados = new javax.swing.JLabel();
        pNomeCompleto = new javax.swing.JPanel();
        lblNomeCompleto = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        pUsuario = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pSenha = new javax.swing.JPanel();
        lblSenha = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        pEmail = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        pTelefone = new javax.swing.JPanel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        pClose = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pLayout.setBackground(new java.awt.Color(0, 0, 47));

        lblImagemCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagemCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/login.png"))); // NOI18N

        lblCadastrese.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        lblCadastrese.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastrese.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastrese.setText("Cadastre-se!");

        javax.swing.GroupLayout pLayoutLayout = new javax.swing.GroupLayout(pLayout);
        pLayout.setLayout(pLayoutLayout);
        pLayoutLayout.setHorizontalGroup(
            pLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLayoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagemCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pLayoutLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblCadastrese)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        pLayoutLayout.setVerticalGroup(
            pLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLayoutLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(lblImagemCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCadastrese)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        getContentPane().add(pLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 421));

        pDados.setBackground(new java.awt.Color(255, 255, 255));
        pDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDados.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        lblDados.setForeground(new java.awt.Color(102, 102, 102));
        lblDados.setText("Dados");
        pDados.add(lblDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        pNomeCompleto.setBackground(new java.awt.Color(255, 255, 255));
        pNomeCompleto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pNomeCompleto.setLayout(new java.awt.BorderLayout());

        lblNomeCompleto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/nomeCompleto.png"))); // NOI18N
        pNomeCompleto.add(lblNomeCompleto, java.awt.BorderLayout.LINE_START);

        txtNomeCompleto.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeCompleto.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        txtNomeCompleto.setForeground(new java.awt.Color(204, 204, 204));
        txtNomeCompleto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNomeCompleto.setText("Nome Completo");
        txtNomeCompleto.setBorder(null);
        txtNomeCompleto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeCompletoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeCompletoFocusLost(evt);
            }
        });
        pNomeCompleto.add(txtNomeCompleto, java.awt.BorderLayout.CENTER);

        pDados.add(pNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 300, 40));

        pUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pUsuario.setLayout(new java.awt.BorderLayout());

        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/usuario.png"))); // NOI18N
        pUsuario.add(lblUsuario, java.awt.BorderLayout.LINE_START);

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Nome de Usuário (Login)");
        txtUsuario.setBorder(null);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        pUsuario.add(txtUsuario, java.awt.BorderLayout.CENTER);

        pDados.add(pUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 300, 40));

        pSenha.setBackground(new java.awt.Color(255, 255, 255));
        pSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/eye.png"))); // NOI18N
        lblSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPasswordField1.setText("Senha");
        jPasswordField1.setBorder(null);
        jPasswordField1.setEchoChar('\u0000');

        javax.swing.GroupLayout pSenhaLayout = new javax.swing.GroupLayout(pSenha);
        pSenha.setLayout(pSenhaLayout);
        pSenhaLayout.setHorizontalGroup(
            pSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSenhaLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pSenhaLayout.setVerticalGroup(
            pSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSenhaLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSenhaLayout.createSequentialGroup()
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pDados.add(pSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 300, 40));

        pEmail.setBackground(new java.awt.Color(255, 255, 255));
        pEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pEmail.setLayout(new java.awt.BorderLayout());

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/gmail.png"))); // NOI18N
        pEmail.add(lblEmail, java.awt.BorderLayout.LINE_START);

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmail.setText("E-mail");
        txtEmail.setBorder(null);
        pEmail.add(txtEmail, java.awt.BorderLayout.CENTER);

        pDados.add(pEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 300, 40));

        pTelefone.setBackground(new java.awt.Color(255, 255, 255));
        pTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pTelefone.setLayout(new java.awt.BorderLayout());

        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/telefone.png"))); // NOI18N
        pTelefone.add(lblTelefone, java.awt.BorderLayout.LINE_START);

        txtTelefone.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefone.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefone.setText("Telefone");
        txtTelefone.setBorder(null);
        pTelefone.add(txtTelefone, java.awt.BorderLayout.CENTER);

        pDados.add(pTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 300, 40));

        pClose.setBackground(new java.awt.Color(0, 0, 47));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/delete_32px.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pCloseLayout = new javax.swing.GroupLayout(pClose);
        pClose.setLayout(pCloseLayout);
        pCloseLayout.setHorizontalGroup(
            pCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCloseLayout.createSequentialGroup()
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pCloseLayout.setVerticalGroup(
            pCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClose, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pDados.add(pClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 40, 40));

        getContentPane().add(pDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 370, 421));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void txtNomeCompletoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCompletoFocusGained
        // TODO add your handling code here:
        if(txtNomeCompleto.getText().equals("Nome Completo")) {
            txtNomeCompleto.setText("");
            txtNomeCompleto.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_txtNomeCompletoFocusGained

    private void txtNomeCompletoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCompletoFocusLost
        // TODO add your handling code here:
        if(txtNomeCompleto.getText().equals("")) {
            txtNomeCompleto.setText("Nome Completo");
            txtNomeCompleto.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtNomeCompletoFocusLost

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        // TODO add your handling code here:
        if(txtUsuario.getText().equals("Nome de Usuário (Login)")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        // TODO add your handling code here:
        if(txtUsuario.getText().equals("")) {
            txtUsuario.setText("Nome de Usuário (Login)");
            txtUsuario.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblCadastrese;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDados;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblImagemCadastro;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pClose;
    private javax.swing.JPanel pDados;
    private javax.swing.JPanel pEmail;
    private javax.swing.JPanel pLayout;
    private javax.swing.JPanel pNomeCompleto;
    private javax.swing.JPanel pSenha;
    private javax.swing.JPanel pTelefone;
    private javax.swing.JPanel pUsuario;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
