/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadorrequisitos.painels;

/**
 *
 * @author allan
 */
public class AlertLogin extends javax.swing.JDialog {

    /**
     * Creates new form Alert
     */
    public AlertLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        this.setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrincipal = new javax.swing.JPanel();
        pIcone = new javax.swing.JPanel();
        lblIcone = new javax.swing.JLabel();
        pDesc = new javax.swing.JPanel();
        pButton = new javax.swing.JPanel();
        lblOk = new javax.swing.JLabel();
        lblDesc2 = new javax.swing.JLabel();
        lblDesc1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        pPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pIcone.setBackground(new java.awt.Color(204, 204, 204));
        pIcone.setPreferredSize(new java.awt.Dimension(200, 189));

        lblIcone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadorrequisitos/imagens/cross.png"))); // NOI18N

        javax.swing.GroupLayout pIconeLayout = new javax.swing.GroupLayout(pIcone);
        pIcone.setLayout(pIconeLayout);
        pIconeLayout.setHorizontalGroup(
            pIconeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIconeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcone, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        pIconeLayout.setVerticalGroup(
            pIconeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIconeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcone, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        pPrincipal.add(pIcone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pDesc.setBackground(new java.awt.Color(255, 255, 255));

        pButton.setBackground(new java.awt.Color(0, 0, 47));
        pButton.setLayout(new java.awt.BorderLayout());

        lblOk.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        lblOk.setForeground(new java.awt.Color(255, 255, 255));
        lblOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOk.setText("OK");
        lblOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOkMouseClicked(evt);
            }
        });
        pButton.add(lblOk, java.awt.BorderLayout.CENTER);

        lblDesc2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        lblDesc2.setForeground(new java.awt.Color(51, 51, 51));
        lblDesc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesc2.setText("Verifique!");

        lblDesc1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        lblDesc1.setForeground(new java.awt.Color(51, 51, 51));
        lblDesc1.setText("Usuário ou senha estão incorretos.");

        javax.swing.GroupLayout pDescLayout = new javax.swing.GroupLayout(pDesc);
        pDesc.setLayout(pDescLayout);
        pDescLayout.setHorizontalGroup(
            pDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDescLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pDescLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesc2)
                    .addComponent(lblDesc1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDescLayout.setVerticalGroup(
            pDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDescLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblDesc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDesc2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pPrincipal.add(pDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 270, 190));

        getContentPane().add(pPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOkMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_lblOkMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDesc1;
    private javax.swing.JLabel lblDesc2;
    private javax.swing.JLabel lblIcone;
    private javax.swing.JLabel lblOk;
    private javax.swing.JPanel pButton;
    private javax.swing.JPanel pDesc;
    private javax.swing.JPanel pIcone;
    private javax.swing.JPanel pPrincipal;
    // End of variables declaration//GEN-END:variables
}
